// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: computeallocation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ComputeAllocationInventory - inventory info for all ComputeAllocations periodically collected
type ComputeAllocationInventory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of ComputeAllocations
	Allocations []*ComputeAllocation `protobuf:"bytes,1,rep,name=allocations,proto3" json:"allocations,omitempty"`
	// Reported timestamp of inventory
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Status of Inventory
	InventoryStatus InventoryStatus `protobuf:"varint,3,opt,name=inventory_status,json=inventoryStatus,proto3,enum=workflows.v1.InventoryStatus" json:"inventory_status,omitempty"`
	// Message for status
	StatusMsg string `protobuf:"bytes,4,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	// Inventory page information
	InventoryPage *InventoryPage `protobuf:"bytes,5,opt,name=inventory_page,json=inventoryPage,proto3" json:"inventory_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeAllocationInventory) Reset() {
	*x = ComputeAllocationInventory{}
	mi := &file_computeallocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeAllocationInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeAllocationInventory) ProtoMessage() {}

func (x *ComputeAllocationInventory) ProtoReflect() protoreflect.Message {
	mi := &file_computeallocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeAllocationInventory.ProtoReflect.Descriptor instead.
func (*ComputeAllocationInventory) Descriptor() ([]byte, []int) {
	return file_computeallocation_proto_rawDescGZIP(), []int{0}
}

func (x *ComputeAllocationInventory) GetAllocations() []*ComputeAllocation {
	if x != nil {
		return x.Allocations
	}
	return nil
}

func (x *ComputeAllocationInventory) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ComputeAllocationInventory) GetInventoryStatus() InventoryStatus {
	if x != nil {
		return x.InventoryStatus
	}
	return InventoryStatus_INVENTORY_STATUS_UNSPECIFIED
}

func (x *ComputeAllocationInventory) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *ComputeAllocationInventory) GetInventoryPage() *InventoryPage {
	if x != nil {
		return x.InventoryPage
	}
	return nil
}

var File_computeallocation_proto protoreflect.FileDescriptor

const file_computeallocation_proto_rawDesc = "" +
	"\n" +
	"\x17computeallocation.proto\x12\fworkflows.v1\x1a\x0eworkflow.proto\x1a\x13forge_carbide.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x02\n" +
	"\x1aComputeAllocationInventory\x12:\n" +
	"\vallocations\x18\x01 \x03(\v2\x18.forge.ComputeAllocationR\vallocations\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12H\n" +
	"\x10inventory_status\x18\x03 \x01(\x0e2\x1d.workflows.v1.InventoryStatusR\x0finventoryStatus\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x04 \x01(\tR\tstatusMsg\x12B\n" +
	"\x0einventory_page\x18\x05 \x01(\v2\x1b.workflows.v1.InventoryPageR\rinventoryPageBCZAgithub.com/NVIDIA/ncx-infra-controller-rest/workflow-schema/protob\x06proto3"

var (
	file_computeallocation_proto_rawDescOnce sync.Once
	file_computeallocation_proto_rawDescData []byte
)

func file_computeallocation_proto_rawDescGZIP() []byte {
	file_computeallocation_proto_rawDescOnce.Do(func() {
		file_computeallocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_computeallocation_proto_rawDesc), len(file_computeallocation_proto_rawDesc)))
	})
	return file_computeallocation_proto_rawDescData
}

var file_computeallocation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_computeallocation_proto_goTypes = []any{
	(*ComputeAllocationInventory)(nil), // 0: workflows.v1.ComputeAllocationInventory
	(*ComputeAllocation)(nil),          // 1: forge.ComputeAllocation
	(*timestamppb.Timestamp)(nil),      // 2: google.protobuf.Timestamp
	(InventoryStatus)(0),               // 3: workflows.v1.InventoryStatus
	(*InventoryPage)(nil),              // 4: workflows.v1.InventoryPage
}
var file_computeallocation_proto_depIdxs = []int32{
	1, // 0: workflows.v1.ComputeAllocationInventory.allocations:type_name -> forge.ComputeAllocation
	2, // 1: workflows.v1.ComputeAllocationInventory.timestamp:type_name -> google.protobuf.Timestamp
	3, // 2: workflows.v1.ComputeAllocationInventory.inventory_status:type_name -> workflows.v1.InventoryStatus
	4, // 3: workflows.v1.ComputeAllocationInventory.inventory_page:type_name -> workflows.v1.InventoryPage
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_computeallocation_proto_init() }
func file_computeallocation_proto_init() {
	if File_computeallocation_proto != nil {
		return
	}
	file_workflow_proto_init()
	file_forge_carbide_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_computeallocation_proto_rawDesc), len(file_computeallocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_computeallocation_proto_goTypes,
		DependencyIndexes: file_computeallocation_proto_depIdxs,
		MessageInfos:      file_computeallocation_proto_msgTypes,
	}.Build()
	File_computeallocation_proto = out.File
	file_computeallocation_proto_goTypes = nil
	file_computeallocation_proto_depIdxs = nil
}
